name: Sugestão de Melhoria / Provedor
description: Sugira uma nova funcionalidade, provedor ou melhoria para o 9RTKSync
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Ideias e sugestões da comunidade de desenvolvedores são muito bem-vindas!
  - type: textarea
    id: problem
    attributes:
      label: Qual problema essa funcionalidade resolve?
      description: Explique o caso de uso ou limitação atual
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Descrição da Solução Proposta
      description: Como você imagina o funcionamento deste novo recurso?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Há algum contorno ou outra ferramenta similar que você já testou?
